# Generated by Django 4.0.1 on 2022-01-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dukaanBanao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('storeURL', models.URLField(max_length=50)),
                ('account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukaanBanao.account')),
            ],
        ),
    ]
