# Generated by Django 4.0.1 on 2022-01-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaanBanao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phNumber', models.BigIntegerField(unique=True)),
                ('otp', models.IntegerField()),
                ('token', models.CharField(max_length=500)),
            ],
        ),
    ]
