# Generated by Django 4.0.1 on 2022-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaanBanao', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('MRP', models.DecimalField(decimal_places=4, max_digits=8)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
