# Generated by Django 4.0.1 on 2022-01-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dukaanBanao', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukaanBanao.customer')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukaanBanao.product')),
                ('store_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukaanBanao.store')),
            ],
        ),
    ]
