# Generated by Django 4.0.1 on 2022-01-23 20:52

from django.db import migrations, models
import dukaanBanao.models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaanBanao', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to=dukaanBanao.models.upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(to='dukaanBanao.image'),
        ),
    ]
